-- Estabelecimentos (matriz e filiais) pertencentes a uma empresa.
CREATE TABLE IF NOT EXISTS `estabelecimento` (
  `id_estabelecimento` int(11) NOT NULL AUTO_INCREMENT,
  `id_empresa` int(11) NOT NULL,
  `tipo_estabelecimento` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1=Matriz, 2=Filial',
  `razao_social` varchar(60) DEFAULT NULL,
  `nome_estabelecimento` varchar(100) NOT NULL,
  `tipo_pessoa` tinyint(4) NOT NULL DEFAULT '1',
  `cnpj_cpf` varchar(20) DEFAULT NULL,
  `tel_fixo` varchar(20) DEFAULT NULL,
  `tel_cel` varchar(20) DEFAULT NULL,
  `email_contato` varchar(60) DEFAULT NULL,
  `cep` varchar(15) DEFAULT NULL,
  `endereco` varchar(50) DEFAULT NULL,
  `numero` varchar(15) DEFAULT NULL,
  `complemento` varchar(45) DEFAULT NULL,
  `bairro` varchar(45) DEFAULT NULL,
  `cod_cidade` int(11) DEFAULT NULL,
  `caminho_logo` varchar(100) DEFAULT NULL,
  `conta_padrao` int(11) DEFAULT NULL,
  `metodo_pagamento_frente_caixa` int(11) DEFAULT NULL,
  `centro_custo_frente_caixa` varchar(60) DEFAULT NULL,
  `conta_contabil_frente_caixa` varchar(60) DEFAULT NULL,
  `centro_custo_vendas` varchar(60) DEFAULT NULL,
  `conta_contabil_vendas` varchar(60) DEFAULT NULL,
  `centro_custo_compras` varchar(60) DEFAULT NULL,
  `conta_contabil_compras` varchar(60) DEFAULT NULL,
  `natureza_caixa` int(11) DEFAULT NULL,
  `insc_estadual` varchar(45) DEFAULT NULL,
  `isenta_ie` tinyint(1) NOT NULL DEFAULT '0',
  `versao_nfe` varchar(10) DEFAULT NULL,
  `ambiente_nfe` int(11) DEFAULT NULL,
  `schema_nfe` varchar(50) NOT NULL DEFAULT '',
  `serie` varchar(15) DEFAULT NULL,
  `serie_nfce` varchar(15) DEFAULT NULL,
  `modelo` char(5) NOT NULL DEFAULT '',
  `modelo_nfce` char(5) NOT NULL DEFAULT '',
  `csc` varchar(100) DEFAULT NULL,
  `csc_id` varchar(45) DEFAULT NULL,
  `codigo_regime_tributario` char(1) NOT NULL DEFAULT '',
  `num_ultima_nf` int(11) DEFAULT NULL,
  `num_ultima_nfce` int(11) DEFAULT NULL,
  `percentual_credito_sn` decimal(5,2) NOT NULL DEFAULT '0.00',
  `caminho_certificado` varchar(100) DEFAULT NULL,
  `senha_certificado` varchar(100) DEFAULT NULL,
  `integ_vendas_externas` tinyint(1) NOT NULL DEFAULT '0',
  `integ_usuario_vendas_externas` varchar(60) NOT NULL DEFAULT '',
  `integ_senha_vendas_externas` varchar(60) NOT NULL DEFAULT '',
  `cred_devol_vendas_externas` varchar(100) DEFAULT NULL,
  `custo_folha` decimal(10,2) NOT NULL DEFAULT '0.00',
  `horas_consideradas` decimal(10,1) NOT NULL DEFAULT '220.0',
  `clientes_ativos` int(11) NOT NULL DEFAULT '60',
  `clientes_inativos_recentes` int(11) NOT NULL DEFAULT '90',
  `criado_em` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_estabelecimento`),
  KEY `idx_estabelecimento_empresa` (`id_empresa`),
  KEY `idx_estabelecimento_documento` (`id_empresa`, `cnpj_cpf`),
  CONSTRAINT `fk_estabelecimento_empresa` FOREIGN KEY (`id_empresa`) REFERENCES `empresa` (`id_empresa`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
